/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sedceng.padfoundation.view;

import com.sedceng.padfoundation.controller.UserInputController;
import com.sedceng.padfoundation.controller.UserInputControllerForReinforcementDesign;
import com.sedceng.padfoundation.dto.FoundationGeometryDto;
import com.sedceng.padfoundation.dto.ReinforcementDto;
import com.sedceng.padfoundation.dto.ServiceabilityLoadsDto;
import com.sedceng.padfoundation.dto.SoilPropertiesNewDto;
import com.sedceng.padfoundation.dto.UltimateLoadsDto;
import com.sedceng.padfoundation.util.ReinforcementCalculatorUtil;
import com.sedceng.padfoundation.util.ShearReinforcementCalculatorUtil;
import com.sedceng.padfoundation.util.SoilPressureCalculatorUtil;
import com.sedceng.padfoundation.util.ValidationUtil;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanduni Navoda
 */
public class SoilReportView extends javax.swing.JFrame {
    
    private UserInputController inputController;
    private UserInputControllerForReinforcementDesign reinforcementInputController;
    /**
     * Creates new form GuestView
     */
    public SoilReportView() {
        inputController = new UserInputController();
        reinforcementInputController = new UserInputControllerForReinforcementDesign();
        initComponents();
        ValidationUtil.applyDoubleFilterToAllTextFields(this);
        setupTabChangeListener();
    }
    
    private void setupTabChangeListener() {
        jTabbedPane1.addChangeListener(e -> {
            int selectedIndex = jTabbedPane1.getSelectedIndex();
            String selectedTitle = jTabbedPane1.getTitleAt(selectedIndex);

            if ("Check Stability".equals(selectedTitle)) {
                if (!ValidationUtil.validateRequiredFields(this)) {
                    return; // Skip further processing
                }
                performStabilityCheck();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        bearingCapacity = new javax.swing.JLabel();
        unitWeightOfSoil = new javax.swing.JLabel();
        internalFrictionAngle = new javax.swing.JLabel();
        frictionAngleConcreteAndSoil = new javax.swing.JLabel();
        cohesion = new javax.swing.JLabel();
        waterTableLocation = new javax.swing.JLabel();
        tfBearignCapacity = new javax.swing.JTextField();
        tfUnitWeightOfSoil = new javax.swing.JTextField();
        tfInternalFrictionAngle = new javax.swing.JTextField();
        tfFrictionAngleFoundationAndSoil = new javax.swing.JTextField();
        tfCohesion = new javax.swing.JTextField();
        rbYes = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        depthOfWaterTable = new javax.swing.JLabel();
        UnitWeightOfWater = new javax.swing.JLabel();
        gammaWat = new javax.swing.JLabel();
        SaturatedUnitWeightOfSoil = new javax.swing.JLabel();
        tfWaterTableDepth = new javax.swing.JTextField();
        tfSaturatedUnitWeight = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        foundationDepth = new javax.swing.JTextField();
        sideLenghtOfFooting = new javax.swing.JTextField();
        heightOfFooting = new javax.swing.JTextField();
        sideLenghtOfColumn = new javax.swing.JTextField();
        columnHeightAboveGround = new javax.swing.JTextField();
        columnHeightBelowGround = new javax.swing.JTextField();
        unitWeightOfConcrete = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSlsCompressiveForce = new javax.swing.JTextField();
        txtSlsTensileForce = new javax.swing.JTextField();
        txtSlsHorizontalTransverseForce = new javax.swing.JTextField();
        txtSlsHorizontalLongitudinalForce = new javax.swing.JTextField();
        txtUlsCompressiveForce1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtUlsTensileForce = new javax.swing.JTextField();
        txtUlsHorizontalTransverseForce = new javax.swing.JTextField();
        txtUlsHorizntalLongitudinalForce = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtFy = new javax.swing.JTextField();
        txtFcu = new javax.swing.JTextField();
        txtCover = new javax.swing.JTextField();
        txtBarDia = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtShearLinksDia = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        btnRfDesign = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lblAsReqComForSagging = new javax.swing.JLabel();
        lblAsProvComForSagging = new javax.swing.JLabel();
        lblProvComRfConfigForSagging = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        lblAsProvComForHogging = new javax.swing.JLabel();
        lblProvComRfConfigForHogging = new javax.swing.JLabel();
        lblAsReqComForHogging = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        lblAsReqTensForSagging = new javax.swing.JLabel();
        lblProvTensRfConfigForSagging = new javax.swing.JLabel();
        lblAsProvTensForSagging = new javax.swing.JLabel();
        lblAsReqTensForHogging = new javax.swing.JLabel();
        lblProvTensRfConfigForHogging = new javax.swing.JLabel();
        lblAsProvTensForHogging = new javax.swing.JLabel();
        lblAsvReq = new javax.swing.JLabel();
        lblShearRefConfig = new javax.swing.JLabel();
        txtNoOfLegs = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bearingCapacity.setText("Safe bearing capacity of soil : ");

        unitWeightOfSoil.setText("Bulk unit weight of soil : ");

        internalFrictionAngle.setText("Effective soil Angle of Internal Friction (Ø’)  : ");

        frictionAngleConcreteAndSoil.setText("Friction angle between concrete foundation and soil (δ)  : ");

        cohesion.setText("Effective soil Cohesion/ Adhesion (c’)  : ");

        waterTableLocation.setText("Water Table is Above the Footing ? :");

        tfBearignCapacity.setText("250");

        tfUnitWeightOfSoil.setText("17.7");

        tfInternalFrictionAngle.setText("32");

        tfFrictionAngleFoundationAndSoil.setText("24");
        tfFrictionAngleFoundationAndSoil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFrictionAngleFoundationAndSoilActionPerformed(evt);
            }
        });

        tfCohesion.setText("8");

        rbYes.setText("Yes");
        rbYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbYesActionPerformed(evt);
            }
        });

        rbNo.setText("No");

        depthOfWaterTable.setText("Depth of Water Table (m)  : ");

        UnitWeightOfWater.setText("Unit Weight of Water (kN/m3)  : ");

        gammaWat.setText("9.81");

        SaturatedUnitWeightOfSoil.setText("Saturated Unit Weight of Soil (kN/m3)  : ");

        tfWaterTableDepth.setText("10");

        tfSaturatedUnitWeight.setText("19");

        jLabel33.setText("kN/m2");

        jLabel34.setText("kN/m3");

        jLabel35.setText("kN/m2");

        jLabel36.setText("m");

        jLabel37.setText("kN/m3");

        jLabel38.setText("kN/m3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SaturatedUnitWeightOfSoil)
                    .addComponent(depthOfWaterTable)
                    .addComponent(waterTableLocation)
                    .addComponent(cohesion)
                    .addComponent(bearingCapacity)
                    .addComponent(unitWeightOfSoil)
                    .addComponent(internalFrictionAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frictionAngleConcreteAndSoil)
                    .addComponent(UnitWeightOfWater))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfBearignCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfUnitWeightOfSoil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34))
                    .addComponent(tfInternalFrictionAngle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFrictionAngleFoundationAndSoil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfCohesion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbYes)
                        .addGap(18, 18, 18)
                        .addComponent(rbNo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfWaterTableDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfSaturatedUnitWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gammaWat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bearingCapacity)
                    .addComponent(tfBearignCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitWeightOfSoil)
                    .addComponent(tfUnitWeightOfSoil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internalFrictionAngle)
                    .addComponent(tfInternalFrictionAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frictionAngleConcreteAndSoil)
                    .addComponent(tfFrictionAngleFoundationAndSoil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cohesion)
                    .addComponent(tfCohesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterTableLocation)
                    .addComponent(rbYes)
                    .addComponent(rbNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depthOfWaterTable)
                    .addComponent(tfWaterTableDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaturatedUnitWeightOfSoil)
                    .addComponent(tfSaturatedUnitWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnitWeightOfWater)
                    .addComponent(gammaWat)
                    .addComponent(jLabel38))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Soil Report Details", jPanel1);

        jLabel1.setText("Foundation Depth");

        jLabel2.setText("Side Lenght of Footing");

        jLabel3.setText("Height of Footing");

        jLabel4.setText("Side Lenght of Column");

        jLabel5.setText("Column Height Above Ground");

        jLabel6.setText("Column Height Below Ground");

        jLabel7.setText("Unit Weight of Concrete");

        foundationDepth.setText("3");
        foundationDepth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foundationDepthActionPerformed(evt);
            }
        });

        sideLenghtOfFooting.setText("3.8");
        sideLenghtOfFooting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sideLenghtOfFootingActionPerformed(evt);
            }
        });

        heightOfFooting.setText("0.6");

        sideLenghtOfColumn.setText("0.6");

        columnHeightAboveGround.setText("0.3");

        columnHeightBelowGround.setText("2.4");
        columnHeightBelowGround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnHeightBelowGroundActionPerformed(evt);
            }
        });

        unitWeightOfConcrete.setText("24");

        jLabel14.setText("m");

        jLabel15.setText("m");

        jLabel16.setText("m");

        jLabel17.setText("m");

        jLabel22.setText("m");

        jLabel23.setText("m");

        jLabel24.setText("kN/m3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addComponent(jLabel5)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(foundationDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sideLenghtOfFooting, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(heightOfFooting, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sideLenghtOfColumn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(columnHeightAboveGround, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(unitWeightOfConcrete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(columnHeightBelowGround, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(foundationDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sideLenghtOfFooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(heightOfFooting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sideLenghtOfColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(columnHeightAboveGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(columnHeightBelowGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(unitWeightOfConcrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Foundation Geometry", jPanel2);

        jLabel8.setText("Serviceability Loads");

        jLabel9.setText("Ultimate Loads");

        jLabel10.setText("Compression Force (Fc)");

        jLabel11.setText("Tensile Force (Ft)");

        jLabel12.setText("Horizontal Transverse Force (Vt)");

        jLabel13.setText("Horizontal Longitudinal Force (Vl)");

        txtSlsCompressiveForce.setText("865");

        txtSlsTensileForce.setText("775");

        txtSlsHorizontalTransverseForce.setText("63");
        txtSlsHorizontalTransverseForce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlsHorizontalTransverseForceActionPerformed(evt);
            }
        });

        txtSlsHorizontalLongitudinalForce.setText("63");

        txtUlsCompressiveForce1.setText("1502");

        jLabel18.setText("Compression Force (Fc)");

        jLabel19.setText("Tensile Force (Ft)");

        jLabel20.setText("Horizontal Transverse Force (Vt)");

        jLabel21.setText("Horizontal Longitudinal Force (Vl)");

        txtUlsTensileForce.setText("1405");

        txtUlsHorizontalTransverseForce.setText("110");
        txtUlsHorizontalTransverseForce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUlsHorizontalTransverseForceActionPerformed(evt);
            }
        });

        txtUlsHorizntalLongitudinalForce.setText("110");

        jLabel25.setText("kN");

        jLabel26.setText("kN");

        jLabel27.setText("kN");

        jLabel28.setText("kN");

        jLabel29.setText("kN");

        jLabel30.setText("kN");

        jLabel31.setText("kN");

        jLabel32.setText("kN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUlsCompressiveForce1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUlsTensileForce, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUlsHorizontalTransverseForce, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUlsHorizntalLongitudinalForce, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSlsCompressiveForce, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSlsTensileForce, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSlsHorizontalTransverseForce, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSlsHorizontalLongitudinalForce, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSlsCompressiveForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSlsTensileForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSlsHorizontalTransverseForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSlsHorizontalLongitudinalForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtUlsCompressiveForce1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUlsTensileForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtUlsHorizontalTransverseForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtUlsHorizntalLongitudinalForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Loads", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Check Stability", jPanel4);

        jLabel39.setText("Yield Strenght of Reinforcement (fy)");

        jLabel40.setText("Grade of Concrete");

        jLabel41.setText("Clear Cover to Reinforcement");

        jLabel42.setText("Bar Diameter (Main Reinforcement)");

        txtFy.setText("500");

        txtFcu.setText("25");
        txtFcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFcuActionPerformed(evt);
            }
        });

        txtCover.setText("50");

        txtBarDia.setText("16");

        jLabel43.setText("mm");

        jLabel44.setText("MPa");

        jLabel45.setText("mm");

        jLabel46.setText("Bar Diameter (Shear Links)");

        txtShearLinksDia.setText("10");

        jLabel47.setText("mm");

        btnRfDesign.setText("Design");
        btnRfDesign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRfDesignActionPerformed(evt);
            }
        });

        jLabel48.setText("Compressive Reinforcement");

        jLabel49.setText("Tensile Reinforcement");

        lblAsReqComForSagging.setText("jLabel51");

        lblAsProvComForSagging.setText("jLabel51");

        lblProvComRfConfigForSagging.setText("jLabel51");

        jLabel51.setText("Sagging");

        jLabel52.setText("Hogging");

        jLabel53.setText("Shear");

        jLabel54.setText("As Required");

        jLabel55.setText("As Provided");

        jLabel56.setText("As Required");

        jLabel57.setText("As Provided");

        lblAsProvComForHogging.setText("jLabel51");

        lblProvComRfConfigForHogging.setText("jLabel51");

        lblAsReqComForHogging.setText("jLabel51");

        jLabel58.setText("Asv Required");

        lblAsReqTensForSagging.setText("jLabel51");

        lblProvTensRfConfigForSagging.setText("jLabel51");

        lblAsProvTensForSagging.setText("jLabel51");

        lblAsReqTensForHogging.setText("jLabel51");

        lblProvTensRfConfigForHogging.setText("jLabel51");

        lblAsProvTensForHogging.setText("jLabel51");

        lblAsvReq.setText("jLabel51");

        lblShearRefConfig.setText("jLabel51");

        txtNoOfLegs.setText("2");

        jLabel50.setText("Number of Legs");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel39)
                        .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel50))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(txtShearLinksDia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel47))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtFy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel44))
                                .addComponent(txtFcu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtCover, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel45))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(txtBarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel43)))
                            .addGap(160, 160, 160)))
                    .addComponent(txtNoOfLegs, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel48))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAsReqTensForSagging, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAsReqComForSagging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAsProvComForSagging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProvComRfConfigForSagging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProvTensRfConfigForSagging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAsProvTensForSagging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAsReqComForHogging, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel56)
                                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAsReqTensForHogging, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAsProvComForHogging, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel57)
                                    .addComponent(lblProvComRfConfigForHogging, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProvTensRfConfigForHogging, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAsProvTensForHogging, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnRfDesign)))
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53)
                    .addComponent(jLabel58)
                    .addComponent(lblAsvReq, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShearRefConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtFy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtFcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtCover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtBarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel46)
                    .addComponent(txtShearLinksDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(txtNoOfLegs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRfDesign))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblAsReqComForHogging)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProvComRfConfigForHogging))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56)
                            .addComponent(jLabel57)
                            .addComponent(jLabel58))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel48)
                                    .addComponent(lblAsReqComForSagging)
                                    .addComponent(lblAsProvComForSagging))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProvComRfConfigForSagging))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAsProvComForHogging)
                                    .addComponent(lblAsvReq))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblShearRefConfig)))))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsReqTensForSagging)
                    .addComponent(jLabel49)
                    .addComponent(lblAsProvTensForSagging)
                    .addComponent(lblAsReqTensForHogging)
                    .addComponent(lblAsProvTensForHogging))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvTensRfConfigForSagging)
                    .addComponent(lblProvTensRfConfigForHogging))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reinforcement Details", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUlsHorizontalTransverseForceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUlsHorizontalTransverseForceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUlsHorizontalTransverseForceActionPerformed

    private void txtSlsHorizontalTransverseForceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlsHorizontalTransverseForceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlsHorizontalTransverseForceActionPerformed

    private void columnHeightBelowGroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnHeightBelowGroundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnHeightBelowGroundActionPerformed

    private void foundationDepthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foundationDepthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foundationDepthActionPerformed

    private void rbYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbYesActionPerformed

    private void tfFrictionAngleFoundationAndSoilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFrictionAngleFoundationAndSoilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFrictionAngleFoundationAndSoilActionPerformed

    private void sideLenghtOfFootingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sideLenghtOfFootingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sideLenghtOfFootingActionPerformed

    private void txtFcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFcuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFcuActionPerformed

    private void btnRfDesignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfDesignActionPerformed
        reinforcementDesign();// TODO add your handling code here:
    }//GEN-LAST:event_btnRfDesignActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GuestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SoilReportView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SaturatedUnitWeightOfSoil;
    private javax.swing.JLabel UnitWeightOfWater;
    private javax.swing.JLabel bearingCapacity;
    private javax.swing.JButton btnRfDesign;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel cohesion;
    private javax.swing.JTextField columnHeightAboveGround;
    private javax.swing.JTextField columnHeightBelowGround;
    private javax.swing.JLabel depthOfWaterTable;
    private javax.swing.JTextField foundationDepth;
    private javax.swing.JLabel frictionAngleConcreteAndSoil;
    private javax.swing.JLabel gammaWat;
    private javax.swing.JTextField heightOfFooting;
    private javax.swing.JLabel internalFrictionAngle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAsProvComForHogging;
    private javax.swing.JLabel lblAsProvComForSagging;
    private javax.swing.JLabel lblAsProvTensForHogging;
    private javax.swing.JLabel lblAsProvTensForSagging;
    private javax.swing.JLabel lblAsReqComForHogging;
    private javax.swing.JLabel lblAsReqComForSagging;
    private javax.swing.JLabel lblAsReqTensForHogging;
    private javax.swing.JLabel lblAsReqTensForSagging;
    private javax.swing.JLabel lblAsvReq;
    private javax.swing.JLabel lblProvComRfConfigForHogging;
    private javax.swing.JLabel lblProvComRfConfigForSagging;
    private javax.swing.JLabel lblProvTensRfConfigForHogging;
    private javax.swing.JLabel lblProvTensRfConfigForSagging;
    private javax.swing.JLabel lblShearRefConfig;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbYes;
    private javax.swing.JTextField sideLenghtOfColumn;
    private javax.swing.JTextField sideLenghtOfFooting;
    private javax.swing.JTextField tfBearignCapacity;
    private javax.swing.JTextField tfCohesion;
    private javax.swing.JTextField tfFrictionAngleFoundationAndSoil;
    private javax.swing.JTextField tfInternalFrictionAngle;
    private javax.swing.JTextField tfSaturatedUnitWeight;
    private javax.swing.JTextField tfUnitWeightOfSoil;
    private javax.swing.JTextField tfWaterTableDepth;
    private javax.swing.JTextField txtBarDia;
    private javax.swing.JTextField txtCover;
    private javax.swing.JTextField txtFcu;
    private javax.swing.JTextField txtFy;
    private javax.swing.JTextField txtNoOfLegs;
    private javax.swing.JTextField txtShearLinksDia;
    private javax.swing.JTextField txtSlsCompressiveForce;
    private javax.swing.JTextField txtSlsHorizontalLongitudinalForce;
    private javax.swing.JTextField txtSlsHorizontalTransverseForce;
    private javax.swing.JTextField txtSlsTensileForce;
    private javax.swing.JTextField txtUlsCompressiveForce1;
    private javax.swing.JTextField txtUlsHorizntalLongitudinalForce;
    private javax.swing.JTextField txtUlsHorizontalTransverseForce;
    private javax.swing.JTextField txtUlsTensileForce;
    private javax.swing.JTextField unitWeightOfConcrete;
    private javax.swing.JLabel unitWeightOfSoil;
    private javax.swing.JLabel waterTableLocation;
    // End of variables declaration//GEN-END:variables
    
     private void performStabilityCheck() {
        SoilPropertiesNewDto dto = new SoilPropertiesNewDto();
        dto.setBearingCapacity(Double.parseDouble(tfBearignCapacity.getText()));
        //dto.setBreadthOfColumn(Double.parseDouble(tfBearignCapacity.getText()));
        dto.setBulkUnitWeight(Double.parseDouble(tfUnitWeightOfSoil.getText()));
        dto.setCohesion(Double.parseDouble(tfCohesion.getText()));
        dto.setFrictionAngleWithFoundation(Double.parseDouble(tfFrictionAngleFoundationAndSoil.getText()));
        dto.setInternalFrictionAngle(Double.parseDouble(tfInternalFrictionAngle.getText()));
        dto.setSaturatedUnitWeight(Double.parseDouble(tfSaturatedUnitWeight.getText()));
        dto.setWaterUnitWeight(Double.parseDouble(gammaWat.getText()));
        dto.setWaterTableDepth(Double.parseDouble(tfWaterTableDepth.getText()));
        
        System.out.println(dto.toString());
        
        
        FoundationGeometryDto geometryDto = new FoundationGeometryDto();
        geometryDto.setColumnHeightAboveGround(Double.parseDouble(columnHeightAboveGround.getText()));
        geometryDto.setColumnHeightBelowGround(Double.parseDouble(columnHeightBelowGround.getText()));
        geometryDto.setFoundationDepth(Double.parseDouble(foundationDepth.getText()));
        geometryDto.setHeightOfFooting(Double.parseDouble(heightOfFooting.getText()));
        geometryDto.setSideLenghtOfColumn(Double.parseDouble(sideLenghtOfColumn.getText()));
        geometryDto.setSideLengthOfFooting(Double.parseDouble(sideLenghtOfFooting.getText()));
        geometryDto.setUnitWeightOfConcrete(Double.parseDouble(unitWeightOfConcrete.getText()));
        System.out.println(geometryDto.toString());
        
        ServiceabilityLoadsDto loadsDto = new ServiceabilityLoadsDto();
        loadsDto.setCompressiveForce(Double.parseDouble(txtSlsCompressiveForce.getText()));
        loadsDto.setTensileForce(Double.parseDouble(txtSlsTensileForce.getText()));
        loadsDto.setHorizontalLongitudinalForce(Double.parseDouble(txtSlsHorizontalLongitudinalForce.getText()));
        loadsDto.setHorizontalTransverseForce(Double.parseDouble(txtSlsHorizontalTransverseForce.getText()));
        
        System.out.println(loadsDto.toString());
        
        SoilPressureCalculatorUtil soilCalculator = new SoilPressureCalculatorUtil(dto, geometryDto);
        
        
              
        
        try {
            boolean bearingCheckResult = inputController.fosCheckForBearing(geometryDto, dto, loadsDto, soilCalculator);
            boolean uprootingCheckResult = inputController.fosCheckForUprooting(geometryDto, dto, loadsDto, soilCalculator);
            boolean slidingCheckResult = inputController.fosCheckForSliding(geometryDto, dto, loadsDto, soilCalculator);
            boolean overturningCheckResult = inputController.fosCheckForOverturning(geometryDto, dto, loadsDto, soilCalculator);
            JOptionPane.showMessageDialog(this, bearingCheckResult);
            JOptionPane.showMessageDialog(this, uprootingCheckResult);
            JOptionPane.showMessageDialog(this, slidingCheckResult);
            JOptionPane.showMessageDialog(this, overturningCheckResult);
            
            clear();
            
        } catch (Exception ex) {
            Logger.getLogger(SoilReportView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
     
     private void reinforcementDesign(){
        SoilPropertiesNewDto dto = new SoilPropertiesNewDto();
        dto.setBearingCapacity(Double.parseDouble(tfBearignCapacity.getText()));
        //dto.setBreadthOfColumn(Double.parseDouble(tfBearignCapacity.getText()));
        dto.setBulkUnitWeight(Double.parseDouble(tfUnitWeightOfSoil.getText()));
        dto.setCohesion(Double.parseDouble(tfCohesion.getText()));
        dto.setFrictionAngleWithFoundation(Double.parseDouble(tfFrictionAngleFoundationAndSoil.getText()));
        dto.setInternalFrictionAngle(Double.parseDouble(tfInternalFrictionAngle.getText()));
        dto.setSaturatedUnitWeight(Double.parseDouble(tfSaturatedUnitWeight.getText()));
        dto.setWaterUnitWeight(Double.parseDouble(gammaWat.getText()));
        dto.setWaterTableDepth(Double.parseDouble(tfWaterTableDepth.getText()));
        
        System.out.println(dto.toString());
        
        
        FoundationGeometryDto geometryDto = new FoundationGeometryDto();
        geometryDto.setColumnHeightAboveGround(Double.parseDouble(columnHeightAboveGround.getText()));
        geometryDto.setColumnHeightBelowGround(Double.parseDouble(columnHeightBelowGround.getText()));
        geometryDto.setFoundationDepth(Double.parseDouble(foundationDepth.getText()));
        geometryDto.setHeightOfFooting(Double.parseDouble(heightOfFooting.getText()));
        geometryDto.setSideLenghtOfColumn(Double.parseDouble(sideLenghtOfColumn.getText()));
        geometryDto.setSideLengthOfFooting(Double.parseDouble(sideLenghtOfFooting.getText()));
        geometryDto.setUnitWeightOfConcrete(Double.parseDouble(unitWeightOfConcrete.getText()));
        System.out.println(geometryDto.toString());
        
        UltimateLoadsDto loadsDto = new UltimateLoadsDto();
        loadsDto.setCompressiveForce(Double.parseDouble(txtSlsCompressiveForce.getText()));
        loadsDto.setTensileForce(Double.parseDouble(txtSlsTensileForce.getText()));
        loadsDto.setHorizontalLongitudinalForce(Double.parseDouble(txtSlsHorizontalLongitudinalForce.getText()));
        loadsDto.setHorizontalTransverseForce(Double.parseDouble(txtSlsHorizontalTransverseForce.getText()));
        System.out.println(loadsDto.toString());
        
        ReinforcementDto rfDto = new ReinforcementDto();
        rfDto.setYieldStrenghtOfReinforcement(Double.parseDouble(txtFy.getText()));
        rfDto.setGradeOfConcrete(Double.parseDouble(txtFcu.getText()));
        rfDto.setBarDiameter(Double.parseDouble(txtBarDia.getText()));
        rfDto.setShearLinksDiameter(Double.parseDouble(txtShearLinksDia.getText()));
        rfDto.setNoOfLegs(Integer.parseInt(txtNoOfLegs.getText()));
        System.out.println(rfDto.toString());
        
        
        
        SoilPressureCalculatorUtil soilCalculator = new SoilPressureCalculatorUtil(dto, geometryDto);
        ReinforcementCalculatorUtil rfCalculator = new ReinforcementCalculatorUtil(rfDto, geometryDto);
        ShearReinforcementCalculatorUtil shearRfCalculator = new ShearReinforcementCalculatorUtil();
        

        try {
            double asRequiredForCompressionInSagging = reinforcementInputController.CompressiveRfRequirementForSagging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            double asProvidedForCompressionInSagging = reinforcementInputController.getAsProvided(asRequiredForCompressionInSagging, geometryDto, rfDto, rfCalculator);
            String compressiveRfDesignForSagging = reinforcementInputController.compressiveRfDesignForSagging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            
            double asRequiredForCompressionInHogging = reinforcementInputController.compressiveRfRequirementForHogging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            double asProvidedForCompressionInHogging = reinforcementInputController.getAsProvided(asRequiredForCompressionInHogging, geometryDto, rfDto, rfCalculator);
            String compressiveRfDesignForHogging = reinforcementInputController.compressiveRfDesignForHogging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            
            double asRequiredForTensileInSagging = reinforcementInputController.tensileRfRequirementForSagging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            double asProvidedForTensileInSagging = reinforcementInputController.getAsProvided(asRequiredForTensileInSagging, geometryDto, rfDto, rfCalculator);
            String tensileRfDesignForSagging = reinforcementInputController.tensileRfDesignForSagging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            
            double asRequiredForTensileInHogging = reinforcementInputController.tensileRfRequirementForHogging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            double asProvidedForTensileInHogging = reinforcementInputController.getAsProvided(asRequiredForTensileInHogging, geometryDto, rfDto, rfCalculator);
            String tensileRfDesignForHogging = reinforcementInputController.tensileRfDesignForHogging(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator);
            
            double asv = reinforcementInputController.ShearReinforcementRequirement(geometryDto, dto, rfDto, loadsDto, soilCalculator, rfCalculator, shearRfCalculator);
            double shearLinkDia = rfDto.getShearLinksDiameter();
            int noOfLegs = rfDto.getNoOfLegs();
            String asvDesign = reinforcementInputController.ShearReinforcementDesign(shearRfCalculator, asv, noOfLegs, shearLinkDia);
            
            
            lblAsReqComForSagging.setText(""+asRequiredForCompressionInSagging);
            lblAsProvComForSagging.setText(""+asProvidedForCompressionInSagging);
            lblProvComRfConfigForSagging.setText(compressiveRfDesignForSagging);
            
            lblAsReqComForHogging.setText(""+asRequiredForCompressionInHogging);
            lblAsProvComForHogging.setText(""+asProvidedForCompressionInHogging);
            lblProvComRfConfigForHogging.setText(compressiveRfDesignForHogging);
            
            lblAsReqTensForSagging.setText(""+asRequiredForTensileInSagging);
            lblAsProvTensForSagging.setText(""+asProvidedForTensileInSagging);
            lblProvTensRfConfigForSagging.setText(tensileRfDesignForSagging);
            
            lblAsReqTensForHogging.setText(""+asRequiredForTensileInHogging);
            lblAsProvTensForHogging.setText(""+asProvidedForTensileInHogging);
            lblProvTensRfConfigForHogging.setText(tensileRfDesignForHogging);
            
            lblAsvReq.setText(""+asv);
            lblShearRefConfig.setText(asvDesign);
            
            
        } catch (Exception ex) {
            Logger.getLogger(SoilReportView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
     }
    
    private void clear() {
//        txtGuestId.setText("");
//        txtGuestName.setText("");
//        txtTitle.setText("");
//        txtNic.setText("");
//        txtEmail.setText("");
//        txtContact.setText("");
//        txtAddress.setText("");
    }
    
    

}
